global:
 scrape_interval: 15s 
 evaluation_interval: 15s


scrape_configs:
 - job_name: 'my-flask-app'
   scrape_interval: 5s
   static_configs:
     - targets: ['app:5000']

 - job_name: 'node'
   scrape_interval: 5s
   static_configs:
     - targets: ['nodeexporter:9100']              
