{
 "title": "app",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{http_status=~\"4..|5..\"}[60s])) / sum(rate(app_request_count_total[60s])) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "100 - node_memory_MemFree_bytes / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "RPS Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total[15s]))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[15s])) * 100)"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status)(rate(app_request_count_total[15s]))"
    }
   ]
  }
 ]
}