{
 "title": "app",
 "time": { "from": "2022-04-11T05:25:15.729Z", "to": "2022-04-11T09:25:15.729Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{http_status=~\"4..|5..\"}[60s])) / sum(rate(app_request_count_total[60s])) * 100"
    }
   ]
  },
  {
   "title": "Average memory usage 15s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[15s]) + avg_over_time(node_memory_Cached_bytes[15s]) + avg_over_time(node_memory_Buffers_bytes[15s])) / avg_over_time(node_memory_MemTotal_bytes[15s])))"
    }
   ]
  },
  {
   "title": "RPS Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total[15s]))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[15s])) * 100)"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status)(rate(app_request_count_total[15s]))"
    }
   ]
  }
 ]
}